from __future__ import annotations

from typing import Protocol

from platform_network.schemas.gpu_server import (
    GpuServerCreate,
    GpuServerRecord,
    GpuServerUpdate,
)


class GpuServerRegistry(Protocol):
    def list(self) -> list[GpuServerRecord]: ...
    def get(self, server_id: str) -> GpuServerRecord: ...
    def create(self, payload: GpuServerCreate) -> GpuServerRecord: ...
    def update(self, server_id: str, payload: GpuServerUpdate) -> GpuServerRecord: ...
    def delete(self, server_id: str) -> None: ...
    def set_enabled(self, server_id: str, enabled: bool) -> GpuServerRecord: ...
    def get_token(self, server_id: str) -> str: ...
