from __future__ import annotations

from typing import Protocol

from platform_network.schemas.kubernetes_target import (
    KubernetesTargetCreate,
    KubernetesTargetHealth,
    KubernetesTargetRecord,
    KubernetesTargetUpdate,
)


class KubernetesTargetRegistry(Protocol):
    def list(self) -> list[KubernetesTargetRecord]: ...
    def get(self, target_id: str) -> KubernetesTargetRecord: ...
    def create(self, payload: KubernetesTargetCreate) -> KubernetesTargetRecord: ...
    def update(
        self, target_id: str, payload: KubernetesTargetUpdate
    ) -> KubernetesTargetRecord: ...
    def delete(self, target_id: str) -> None: ...
    def set_enabled(self, target_id: str, enabled: bool) -> KubernetesTargetRecord: ...
    def health(self, target_id: str) -> KubernetesTargetHealth: ...
