{{- if and .Values.master.enabled .Values.ingress.enabled }}
{{- range .Values.ingress.hosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "platform.fullname" $ }}-{{ .name }}
  labels:
    {{- include "platform.labels" $ | nindent 4 }}
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.ingress.className }}
  ingressClassName: {{ $.Values.ingress.className | quote }}
  {{- end }}
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if eq .service "admin" }}
          - path: "/v1/challenges"
            pathType: Prefix
            backend:
              service:
                name: {{ include "platform.fullname" $ }}-proxy
                port:
                  name: http
          {{- end }}
          - path: {{ .path | default "/" | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "platform.fullname" $ }}-{{ .service }}
                port:
                  name: http
---
{{- end }}
{{- end }}
